### ISSUE TITLE
Mission 3 - SRS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [ZeinaAbuSwai/Salametcom#18]
- Mission client feedback.

**Comment by ZeinaAbuSwai** [comment]
@SeifAldenFarhan 
please add a section called "client feedback" to the document, and write there what was Hanin's feedback in your meeting

**Comment by SeifAldenFarhan** [comment]
The issue is done !

**Comment by ZeinaAbuSwai** [comment]
@kob-e changes have been made , please check them

**Comment by ZeinaAbuSwai** [comment]
@kob-e PSA
