### ISSUE TITLE
Mission 5 - ZFR: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [ZeinaAbuSwai/Salametcom#21]
- איטרציה הבאה עדיין בטיוטא
- איפה קישור לאב טיפוס
- אפשר לעשות לדף תוכן עניינים

**Comment by ZeinaAbuSwai** [comment]
@karinmarjieh please add תוכן עניינים for the ZFR document

**Comment by ZeinaAbuSwai** [comment]
added the prototype link to the document

**Comment by ZeinaAbuSwai** [comment]
@kob-e changes have been made, please check them

**Comment by SeifAldenFarhan** [comment]
@kob-e  what do you ,mean by "איטרציה הבאה עדיין בטיוטא"
