### ISSUE TITLE
SRS - 3rd group assignment 

### ISSUE THREAD

**Issue by ZeinaAbuSwai** [ZeinaAbuSwai/Salametcom#3]
https://github.com/ZeinaAbuSwai/Salametcom/wiki/SRS

**Comment by robi-y** [comment]
Detailed use cases, very nice
- Missing 2 members in review
- Actor table: goals for every actor, missing stakeholder - hospital, more actors - paypal
- Use case order, start with UC3
- UC3: remove step1, details output of usecase
- add user story for external scenarios, SMS, facebook

- Nice prototype

**Comment by ZeinaAbuSwai** [comment]
@karinmarjieh: 
- [x] Add the requirement of Arabic. 

- [x] Go over what you wrote and see if there's anything missing.

@fuadsami: 

- [x] Make UC3 the first one.

- [x] Add details to the successful cases.

- [x] Add the UC of login/register.

@SeifAldenFarhan 

- [x] Add user story for signing in/up via facebook

- [x] Add user story for sending sms case.

@hamuda8989 

- [x] Edit the diagram as we discussed.

**Comment by ZeinaAbuSwai** [comment]
@robi-y  we've done all the changes you asked for.

**Comment by robi-y** [comment]
Excellent 💯
