### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [ZeinaAbuSwai/Salametcom#4]
- לא תייגתם אותי בissue שפתחתם
- חסר קצת מידע על הצוות ועל השונות
- צריך להוסיף סיכונים שקשורים בפרויקט עצמו

**Comment by ZeinaAbuSwai** [comment]
Hi Yaacov, 
changes have been made to the risk management and team diversity sections.
Concerning the first point, about opening the issue, when I opened the issue it was a Saturday, I wanted to tag you but you haven't approved the request to be one of the contributors to this project yet. So I tagged myself instead and changed it back to you as soon as I got your approval.

thank you.

**Comment by YaakovHatam** [comment]
Great, you still didn't opened issue for submission for this exercise, next time pay attention to this.
